Repository axiomhq/cli, pull requests merged in 2021-01, with the labels that each got.

#10 Fix auth select command
  .goreleaser.yml
  cmd/axiom/auth/auth_logout.go
  cmd/axiom/auth/auth_select.go
  go.mod
  go.sum
Labels: bug

#17 Update README.md
  README.md
Labels: documentation

#25 Scan in a go func when --flush-every is set
  cmd/axiom/ingest/ingest.go
Labels: bug

#26 Add Docker image
  .dockerignore
  .github/workflows/go.yml
  .goreleaser.yml
  Dockerfile
Labels: enhancement

#27 Remove v prefix from docker tags
  .goreleaser.yml
Labels: enhancement

#30 Make sure all config keys are returned
  internal/config/config.go
Labels: bug

#31 Minimal docker docs
  README.md
Labels: documentation
